// Comprehensive Twilio SMS Compliance Data for 181 Countries
const complianceData = {
    // NORTH AMERICA
    'United States': {
        flag: '🇺🇸',
        compliance: '<ul><li><strong>A2P 10DLC Registration:</strong> Mandatory for application-to-person messaging. Requires brand and campaign registration through TCR.</li><li><strong>TCPA Compliance:</strong> Prior express written consent required for marketing messages.</li><li><strong>CTIA Guidelines:</strong> Must comply with CTIA Messaging Principles including proper opt-in/opt-out mechanisms.</li><li><strong>Carrier Filtering:</strong> Subject to carrier-level spam filtering. Avoid SHAFT violations.</li></ul>',
        recommendedSender: 'A2P 10DLC (10-digit long code with A2P registration)',
        backupSender: 'Toll-Free Number',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Full two-way messaging supported with inbound webhook delivery.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Requires Meta Business verification.',
        rcs: 'Yes',
        rcsNotes: 'RCS is fully supported via Twilio. Requires brand verification and Google RBM platform registration. Supported on Android devices with Google Messages app.'
    },
    'Canada': {
        flag: '🇨🇦',
        compliance: '<ul><li><strong>CASL Compliance:</strong> Canada\'s Anti-Spam Legislation requires express or implied consent.</li><li><strong>CRTC Registration:</strong> Long code campaigns may require registration with Canadian carriers.</li><li><strong>Opt-in Required:</strong> Must obtain clear consent and maintain records.</li></ul>',
        recommendedSender: 'Canadian Long Code (10-digit with carrier registration)',
        backupSender: 'Short Code (5-6 digit)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Full two-way messaging supported on long codes and short codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Good adoption in Canadian market.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via Twilio. Requires brand verification. Available on major Canadian carriers including Rogers, Bell, and Telus.'
    },
    'Mexico': {
        flag: '🇲🇽',
        compliance: '<ul><li><strong>IFT Regulations:</strong> Mexican telecom regulator requirements.</li><li><strong>Data Privacy:</strong> Mexican Federal Law on Protection of Personal Data requires consent.</li><li><strong>Sender Registration:</strong> Long codes should be registered with carriers.</li></ul>',
        recommendedSender: 'Mexican Long Code',
        backupSender: 'Alphanumeric Sender ID (limited support)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Mexican long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption rate in Mexico.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is limited in Mexico. Available on select carriers with Android devices. Telcel and Movistar have partial RCS support.'
    },

    // EUROPE - UK & IRELAND
    'United Kingdom': {
        flag: '🇬🇧',
        compliance: '<ul><li><strong>Ofcom Regulations:</strong> UK telecommunications regulations compliance required.</li><li><strong>PECR Compliance:</strong> Requires soft opt-in for existing customers or explicit consent.</li><li><strong>GDPR:</strong> Full compliance with data protection regulations.</li><li><strong>Sender ID Registration:</strong> Recommended to avoid spoofing blocks.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (11 characters max)',
        backupSender: 'UK Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs do not support inbound. Use UK long codes for two-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Strong adoption rate in UK market.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported via Twilio in the UK. Available on major UK carriers including EE, Vodafone, O2, and Three. Requires Google RBM registration.'
    },
    'Ireland': {
        flag: '🇮🇪',
        compliance: '<ul><li><strong>GDPR:</strong> Full EU data protection compliance required.</li><li><strong>ComReg:</strong> Irish telecom regulator requirements.</li><li><strong>ePrivacy:</strong> Prior consent required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Irish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way. Use Irish long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is growing in Ireland. Available on select carriers with Android devices.'
    },

    // EUROPE - WESTERN
    'Germany': {
        flag: '🇩🇪',
        compliance: '<ul><li><strong>GDPR:</strong> Strict data protection compliance required.</li><li><strong>Bundesnetzagentur:</strong> German telecom regulator requirements.</li><li><strong>Double Opt-in:</strong> Recommended for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'German Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way only. Use German long codes for two-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption rate in Germany.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in Germany via Twilio. Available on Deutsche Telekom, Vodafone, and O2. Requires brand verification.'
    },
    'France': {
        flag: '🇫🇷',
        compliance: '<ul><li><strong>GDPR:</strong> Full EU data protection compliance.</li><li><strong>ARCEP:</strong> French telecom regulator requirements.</li><li><strong>CNIL:</strong> French data protection authority guidelines.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'French Long Code (limited)',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way. French long codes limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Strong user base in France.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via Twilio in France. Available on Orange, SFR, Bouygues Telecom, and Free Mobile.'
    },
    'Spain': {
        flag: '🇪🇸',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance required.</li><li><strong>LSSI:</strong> Spanish Information Society Services Act compliance.</li><li><strong>AEPD:</strong> Spanish Data Protection Agency enforcement.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Spanish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs do not support inbound.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Strong user adoption in Spain.',
        rcs: 'Yes',
        rcsNotes: 'RCS available in Spain via major carriers including Movistar, Orange, and Vodafone.'
    },
    'Italy': {
        flag: '🇮🇹',
        compliance: '<ul><li><strong>GDPR:</strong> Full EU data protection compliance.</li><li><strong>AGCOM:</strong> Italian Communications Authority oversight.</li><li><strong>Privacy Code:</strong> Explicit consent required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Italian Long Code (limited)',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Strong adoption in Italian market.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported in Italy. Available on TIM, Vodafone, and WindTre networks.'
    },
    'Netherlands': {
        flag: '🇳🇱',
        compliance: '<ul><li><strong>GDPR:</strong> Full EU data protection compliance.</li><li><strong>Telecommunications Act:</strong> Dutch telecom law compliance.</li><li><strong>ACM:</strong> Consumer protection enforcement.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Netherlands Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs are one-way only.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption in Netherlands.',
        rcs: 'Yes',
        rcsNotes: 'RCS available via KPN, VodafoneZiggo, and T-Mobile Netherlands.'
    },
    'Belgium': {
        flag: '🇧🇪',
        compliance: '<ul><li><strong>GDPR:</strong> Full EU compliance required.</li><li><strong>BIPT:</strong> Belgian telecom regulator requirements.</li><li><strong>Opt-in:</strong> Prior consent required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Belgian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs do not support inbound messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is growing in Belgium. Available on select carriers.'
    },
    'Switzerland': {
        flag: '🇨🇭',
        compliance: '<ul><li><strong>FADP:</strong> Swiss Federal Act on Data Protection compliance.</li><li><strong>OFCOM:</strong> Swiss telecom regulator requirements.</li><li><strong>Consent:</strong> Required for marketing communications.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Swiss Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs are one-way only.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via Swisscom, Sunrise, and Salt Mobile networks.'
    },
    'Austria': {
        flag: '🇦🇹',
        compliance: '<ul><li><strong>GDPR:</strong> Full EU compliance required.</li><li><strong>RTR:</strong> Austrian telecom regulator requirements.</li><li><strong>TKG:</strong> Telecommunications Act compliance.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Austrian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Use Austrian long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS available via A1 Telekom Austria, Magenta, and Drei.'
    },
    'Portugal': {
        flag: '🇵🇹',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>ANACOM:</strong> Portuguese telecom regulator.</li><li><strong>Opt-in:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Portuguese Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Portugal. Available on select carriers.'
    },
    'Greece': {
        flag: '🇬🇷',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>EETT:</strong> Greek telecom regulator requirements.</li><li><strong>Consent:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Greek Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Greek long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not yet widely supported in Greece.'
    },

    // EUROPE - NORDICS
    'Sweden': {
        flag: '🇸🇪',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>PTS:</strong> Swedish telecom regulator.</li><li><strong>Marketing Act:</strong> Consent required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Swedish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way only.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via Telia, Telenor, and Tre Sweden.'
    },
    'Norway': {
        flag: '🇳🇴',
        compliance: '<ul><li><strong>GDPR:</strong> Data protection compliance.</li><li><strong>Nkom:</strong> Norwegian telecom regulator.</li><li><strong>Marketing Act:</strong> Prior consent required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Norwegian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Use Norwegian long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS available via Telenor Norway, Telia, and Ice.'
    },
    'Denmark': {
        flag: '🇩🇰',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>EUDMA:</strong> Danish telecom regulator.</li><li><strong>Marketing Practices Act:</strong> Consent required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Danish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via TDC, Telenor Denmark, and Telia.'
    },
    'Finland': {
        flag: '🇫🇮',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>Traficom:</strong> Finnish telecom regulator.</li><li><strong>InfoSoc Act:</strong> Prior consent for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Finnish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Finnish long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS available via Elisa, Telia Finland, and DNA.'
    },
    'Iceland': {
        flag: '🇮🇸',
        compliance: '<ul><li><strong>GDPR:</strong> Data protection compliance.</li><li><strong>PFS:</strong> Icelandic telecom regulator.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Icelandic Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely deployed in Iceland.'
    },

    // EUROPE - EASTERN
    'Poland': {
        flag: '🇵🇱',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>UKE:</strong> Polish telecom regulator.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Polish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs do not support inbound.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via Orange Polska, T-Mobile Poland, and Play.'
    },
    'Czech Republic': {
        flag: '🇨🇿',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>CTU:</strong> Czech telecom regulator.</li><li><strong>Opt-in:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Czech Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Czech long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Czech Republic.'
    },
    'Hungary': {
        flag: '🇭🇺',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>NMHH:</strong> Hungarian telecom regulator.</li><li><strong>Prior consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Hungarian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is limited in Hungary.'
    },
    'Romania': {
        flag: '🇷🇴',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>ANCOM:</strong> Romanian telecom regulator.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Romanian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Romania.'
    },
    'Bulgaria': {
        flag: '🇧🇬',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>CRC:</strong> Bulgarian telecom regulator.</li><li><strong>Opt-in:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Bulgarian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely supported in Bulgaria.'
    },
    'Croatia': {
        flag: '🇭🇷',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>HAKOM:</strong> Croatian telecom regulator.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Croatian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Croatian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Croatia.'
    },
    'Serbia': {
        flag: '🇷🇸',
        compliance: '<ul><li><strong>RATEL:</strong> Serbian telecom regulator requirements.</li><li><strong>Data Protection:</strong> Serbian data protection law compliance.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Serbian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Serbia.'
    },
    'Slovakia': {
        flag: '🇸🇰',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>RUT:</strong> Slovak telecom regulator.</li><li><strong>Opt-in:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Slovak Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely deployed in Slovakia.'
    },
    'Slovenia': {
        flag: '🇸🇮',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>AKOS:</strong> Slovenian telecom regulator.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Slovenian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Slovenia.'
    },
    'Estonia': {
        flag: '🇪🇪',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>Consumer Protection:</strong> Estonian regulations.</li><li><strong>Opt-in:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Estonian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Estonian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Estonia.'
    },
    'Latvia': {
        flag: '🇱🇻',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>SPRK:</strong> Latvian telecom regulator.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Latvian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely deployed in Latvia.'
    },
    'Lithuania': {
        flag: '🇱🇹',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>RRT:</strong> Lithuanian telecom regulator.</li><li><strong>Opt-in:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Lithuanian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Lithuania.'
    },

    // ASIA-PACIFIC
    'Australia': {
        flag: '🇦🇺',
        compliance: '<ul><li><strong>Spam Act 2003:</strong> Consent required for commercial messages.</li><li><strong>ACMA:</strong> Australian Communications and Media Authority enforcement.</li><li><strong>Do Not Call Register:</strong> Must screen against register.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (11 characters max)',
        backupSender: 'Australian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs do not support inbound.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via Twilio in Australia. Available on Telstra, Optus, and Vodafone networks.'
    },
    'New Zealand': {
        flag: '🇳🇿',
        compliance: '<ul><li><strong>Unsolicited Electronic Messages Act:</strong> Consent required.</li><li><strong>Commerce Commission:</strong> Enforcement of anti-spam laws.</li><li><strong>Opt-out:</strong> Required in every message.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'New Zealand Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Use long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in New Zealand. Available on select carriers.'
    },
    'Japan': {
        flag: '🇯🇵',
        compliance: '<ul><li><strong>MIC Regulations:</strong> Ministry of Internal Affairs oversight.</li><li><strong>APPI:</strong> Act on Protection of Personal Information.</li><li><strong>Carrier Approval:</strong> Often required for sender IDs.</li></ul>',
        recommendedSender: 'Japanese Long Code',
        backupSender: 'Alphanumeric Sender ID (limited)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Japanese long codes.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp adoption is lower in Japan. SMS and LINE preferred.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in Japan via major carriers including NTT Docomo, au (KDDI), and SoftBank. Requires carrier partnerships.'
    },
    'South Korea': {
        flag: '🇰🇷',
        compliance: '<ul><li><strong>MSIT Regulations:</strong> Ministry of Science and ICT oversight.</li><li><strong>PIPA:</strong> Personal Information Protection Act.</li><li><strong>Real-name Verification:</strong> Required for sender registration.</li><li><strong>080 Rejection Number:</strong> Must provide opt-out number.</li></ul>',
        recommendedSender: 'Korean Long Code (with registration)',
        backupSender: 'N/A (strict local requirements)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging available but requires local business registration.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp has limited adoption. KakaoTalk is the dominant messaging platform.',
        rcs: 'Yes',
        rcsNotes: 'RCS is well-established in South Korea. Supported by SK Telecom, KT, and LG U+. Requires local business registration and carrier approval.'
    },
    'China': {
        flag: '🇨🇳',
        compliance: '<ul><li><strong>MIIT Regulations:</strong> Strict government oversight of all messaging.</li><li><strong>ICP License:</strong> May be required for messaging services.</li><li><strong>Content Censorship:</strong> All messages subject to government filtering.</li><li><strong>Local Partnerships:</strong> Foreign companies must partner with licensed operators.</li></ul>',
        recommendedSender: 'Chinese Long Code (via local partner)',
        backupSender: 'N/A (local partnership mandatory)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Requires local operator partnerships and government compliance.',
        whatsapp: 'No',
        whatsappNotes: 'WhatsApp is blocked in China. Use WeChat (requires separate integration).',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported by major Chinese carriers (China Mobile, China Unicom, China Telecom) but subject to strict government regulations and content filtering. Requires local partnership and approval.'
    },
    'Hong Kong': {
        flag: '🇭🇰',
        compliance: '<ul><li><strong>PDPO:</strong> Personal Data (Privacy) Ordinance.</li><li><strong>OFCA:</strong> Office of the Communications Authority oversight.</li><li><strong>Opt-in:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Hong Kong Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Use Hong Kong long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. High adoption rate.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported via major Hong Kong carriers including PCCW, SmarTone, and 3 Hong Kong.'
    },
    'Taiwan': {
        flag: '🇹🇼',
        compliance: '<ul><li><strong>NCC:</strong> National Communications Commission regulations.</li><li><strong>PDPA:</strong> Personal Data Protection Act.</li><li><strong>Sender Registration:</strong> Required with carriers.</li></ul>',
        recommendedSender: 'Taiwan Long Code',
        backupSender: 'Alphanumeric Sender ID (limited)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Taiwan long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Taiwan. Available on select carriers.'
    },
    'Singapore': {
        flag: '🇸🇬',
        compliance: '<ul><li><strong>IMDA Regulations:</strong> Info-communications Media Development Authority oversight.</li><li><strong>PDPA:</strong> Personal Data Protection Act.</li><li><strong>SSIR Registration:</strong> Mandatory registration with Singapore SMS Sender ID Registry.</li><li><strong>DNC Registry:</strong> Must check Do Not Call registry.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered with SSIR)',
        backupSender: 'Singapore Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric sender IDs are one-way. Use Singapore long codes for two-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Strong adoption in Singapore.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported in Singapore via Singtel, StarHub, and M1. Requires sender registration and SSIR compliance.'
    },
    'Malaysia': {
        flag: '🇲🇾',
        compliance: '<ul><li><strong>MCMC:</strong> Malaysian Communications and Multimedia Commission.</li><li><strong>PDPA:</strong> Personal Data Protection Act.</li><li><strong>Opt-in:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Malaysian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Malaysian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption rate.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Malaysia. Available on select carriers including Maxis and Celcom.'
    },
    'Thailand': {
        flag: '🇹🇭',
        compliance: '<ul><li><strong>NBTC:</strong> National Broadcasting and Telecommunications Commission.</li><li><strong>PDPA:</strong> Personal Data Protection Act (similar to GDPR).</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Thai Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Thailand. LINE is the dominant messaging platform.'
    },
    'Vietnam': {
        flag: '🇻🇳',
        compliance: '<ul><li><strong>MIC:</strong> Ministry of Information and Communications oversight.</li><li><strong>Data Protection:</strong> Vietnamese data protection regulations.</li><li><strong>Brand Registration:</strong> Required with carriers.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Vietnamese Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Vietnam. Zalo is the dominant local messaging platform.'
    },
    'Philippines': {
        flag: '🇵🇭',
        compliance: '<ul><li><strong>NTC:</strong> National Telecommunications Commission.</li><li><strong>Data Privacy Act:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> Required with carriers.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Philippine Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Use Philippine long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely deployed in the Philippines.'
    },
    'Indonesia': {
        flag: '🇮🇩',
        compliance: '<ul><li><strong>KOMINFO:</strong> Ministry of Communication and Information Technology.</li><li><strong>PDP Law:</strong> Personal Data Protection regulations.</li><li><strong>Sender Registration:</strong> Required with local operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Indonesian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Extremely high adoption rate in Indonesia.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Indonesia. Available on Telkomsel and select carriers.'
    },
    'India': {
        flag: '🇮🇳',
        compliance: '<ul><li><strong>TRAI DLT Registration:</strong> Mandatory registration on DLT platforms. All senders, templates, and entities must be registered.</li><li><strong>Template Approval:</strong> All message templates require pre-approval.</li><li><strong>Entity and Sender ID:</strong> Must register entity ID (PE-ID) and 6-character sender ID.</li><li><strong>Content Categories:</strong> Promotional, Transactional, or Service-based with different delivery rules.</li><li><strong>Promotional Restrictions:</strong> 9 AM - 9 PM only. Blocked to NDNC registry numbers.</li></ul>',
        recommendedSender: '6-character Alphanumeric Sender ID (TRAI registered)',
        backupSender: 'N/A (sender ID registration is mandatory)',
        twoWayMessaging: 'No',
        twoWayNotes: 'India does not support two-way messaging for commercial traffic. All SMS is one-way outbound only.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API strongly recommended for two-way engagement. Requires Meta verification and template approval. Very high user adoption in India.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in India via major carriers including Jio, Airtel, and Vodafone Idea. Requires brand verification and compliance with TRAI regulations. Template approval similar to SMS.'
    },
    'Pakistan': {
        flag: '🇵🇰',
        compliance: '<ul><li><strong>PTA:</strong> Pakistan Telecommunication Authority regulations.</li><li><strong>Sender Registration:</strong> Required with local carriers.</li><li><strong>Content Restrictions:</strong> Subject to government content rules.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Pakistani Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Pakistan.'
    },
    'Bangladesh': {
        flag: '🇧🇩',
        compliance: '<ul><li><strong>BTRC:</strong> Bangladesh Telecommunication Regulatory Commission.</li><li><strong>Sender Registration:</strong> Required with carriers.</li><li><strong>Content Rules:</strong> Subject to local regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Bangladesh Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Bangladesh long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Bangladesh.'
    },
    'Sri Lanka': {
        flag: '🇱🇰',
        compliance: '<ul><li><strong>TRCSL:</strong> Telecommunications Regulatory Commission.</li><li><strong>Sender Registration:</strong> Required with operators.</li><li><strong>Opt-in:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Sri Lankan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Sri Lanka.'
    },
    'Nepal': {
        flag: '🇳🇵',
        compliance: '<ul><li><strong>NTA:</strong> Nepal Telecommunications Authority.</li><li><strong>Local Registration:</strong> May require local business registration.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Nepali Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited availability for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Nepal.'
    },

    // MIDDLE EAST
    'United Arab Emirates': {
        flag: '🇦🇪',
        compliance: '<ul><li><strong>TRA:</strong> Telecommunications and Digital Government Regulatory Authority.</li><li><strong>DND Registry:</strong> Do Not Disturb registry compliance required.</li><li><strong>Content Rules:</strong> Strict content filtering for cultural and legal compliance.</li><li><strong>Registration:</strong> Sender ID registration with operators required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (pre-approved)',
        backupSender: 'UAE Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way. Use UAE long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption in UAE.',
        rcs: 'Yes',
        rcsNotes: 'RCS supported in UAE via Etisalat and du. Requires brand verification and compliance with TRA regulations.'
    },
    'Saudi Arabia': {
        flag: '🇸🇦',
        compliance: '<ul><li><strong>CITC:</strong> Communications and Information Technology Commission.</li><li><strong>Sender Registration:</strong> Mandatory registration with Saudi carriers.</li><li><strong>Content Compliance:</strong> Must comply with cultural and religious content rules.</li><li><strong>Opt-in:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Saudi Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Saudi long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. High adoption rate.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in Saudi Arabia via STC, Mobily, and Zain. Requires brand verification and CITC compliance.'
    },
    'Qatar': {
        flag: '🇶🇦',
        compliance: '<ul><li><strong>CRA:</strong> Communications Regulatory Authority.</li><li><strong>Sender Registration:</strong> Required with Qatari operators.</li><li><strong>Content Rules:</strong> Subject to local content regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Qatari Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Qatar via Ooredoo and Vodafone Qatar.'
    },
    'Kuwait': {
        flag: '🇰🇼',
        compliance: '<ul><li><strong>CITRA:</strong> Communications and Information Technology Regulatory Authority.</li><li><strong>Sender Registration:</strong> Required with carriers.</li><li><strong>Content Compliance:</strong> Must follow local content guidelines.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Kuwaiti Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Kuwaiti long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Kuwait.'
    },
    'Bahrain': {
        flag: '🇧🇭',
        compliance: '<ul><li><strong>TRA:</strong> Telecommunications Regulatory Authority.</li><li><strong>Sender Registration:</strong> Required with Bahraini operators.</li><li><strong>Consent:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Bahraini Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Bahrain.'
    },
    'Oman': {
        flag: '🇴🇲',
        compliance: '<ul><li><strong>TRA:</strong> Telecommunications Regulatory Authority.</li><li><strong>Registration:</strong> Sender registration with Omani carriers.</li><li><strong>Content Rules:</strong> Subject to local content regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Omani Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Oman.'
    },
    'Israel': {
        flag: '🇮🇱',
        compliance: '<ul><li><strong>MOC:</strong> Ministry of Communications oversight.</li><li><strong>Privacy Protection Law:</strong> Consent required for marketing.</li><li><strong>Sender Registration:</strong> May be required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Israeli Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Use Israeli long codes for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Israel via major carriers.'
    },
    'Jordan': {
        flag: '🇯🇴',
        compliance: '<ul><li><strong>TRC:</strong> Telecommunications Regulatory Commission.</li><li><strong>Sender Registration:</strong> Required with Jordanian operators.</li><li><strong>Content Rules:</strong> Subject to local regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Jordanian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Jordan.'
    },
    'Lebanon': {
        flag: '🇱🇧',
        compliance: '<ul><li><strong>TRA:</strong> Telecommunications Regulatory Authority.</li><li><strong>Sender Registration:</strong> May be required with carriers.</li><li><strong>Content Rules:</strong> Subject to local regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Lebanese Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Lebanon.'
    },
    'Turkey': {
        flag: '🇹🇷',
        compliance: '<ul><li><strong>BTK:</strong> Information and Communication Technologies Authority.</li><li><strong>KVKK:</strong> Personal Data Protection Law compliance.</li><li><strong>Commercial Message Management System:</strong> Registration required for commercial messages.</li><li><strong>IYS Registration:</strong> Must register with İleti Yönetim Sistemi.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (IYS registered)',
        backupSender: 'Turkish Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way. Use Turkish long codes for two-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption in Turkey.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in Turkey via Turkcell, Vodafone Turkey, and Türk Telekom. Requires IYS registration and brand verification.'
    },
    'Egypt': {
        flag: '🇪🇬',
        compliance: '<ul><li><strong>NTRA:</strong> National Telecom Regulatory Authority.</li><li><strong>Sender Registration:</strong> Required with Egyptian carriers.</li><li><strong>Content Rules:</strong> Subject to government content regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Egyptian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Egyptian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Egypt.'
    },
    'Morocco': {
        flag: '🇲🇦',
        compliance: '<ul><li><strong>ANRT:</strong> National Telecommunications Regulatory Agency.</li><li><strong>Sender Registration:</strong> Required with Moroccan operators.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Moroccan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Morocco.'
    },

    // AFRICA
    'South Africa': {
        flag: '🇿🇦',
        compliance: '<ul><li><strong>POPIA:</strong> Protection of Personal Information Act compliance.</li><li><strong>WASPA:</strong> Wireless Application Service Providers Association code of conduct.</li><li><strong>Opt-in Required:</strong> Double opt-in recommended for subscriptions.</li><li><strong>Content Rules:</strong> Adult content and gambling have additional restrictions.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'South African Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way. Use South African long codes for two-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption in South Africa.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in South Africa via Vodacom, MTN, and Telkom. Requires brand verification and WASPA compliance.'
    },
    'Nigeria': {
        flag: '🇳🇬',
        compliance: '<ul><li><strong>NCC:</strong> Nigerian Communications Commission regulations.</li><li><strong>NDPR:</strong> Nigeria Data Protection Regulation compliance.</li><li><strong>Sender Registration:</strong> Required with Nigerian operators.</li><li><strong>DND List:</strong> Must respect Do Not Disturb registry.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Nigerian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Nigerian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. High adoption rate.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Nigeria. Available on MTN Nigeria and select carriers.'
    },
    'Kenya': {
        flag: '🇰🇪',
        compliance: '<ul><li><strong>CA:</strong> Communications Authority of Kenya.</li><li><strong>Data Protection Act:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> Required with Kenyan operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Kenyan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Kenya.'
    },
    'Ghana': {
        flag: '🇬🇭',
        compliance: '<ul><li><strong>NCA:</strong> National Communications Authority.</li><li><strong>Data Protection Act:</strong> Consent required for commercial messaging.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Ghanaian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Ghanaian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Ghana.'
    },
    'Tanzania': {
        flag: '🇹🇿',
        compliance: '<ul><li><strong>TCRA:</strong> Tanzania Communications Regulatory Authority.</li><li><strong>SIM Registration:</strong> Strict SIM card registration requirements.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Tanzanian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Tanzania.'
    },
    'Uganda': {
        flag: '🇺🇬',
        compliance: '<ul><li><strong>UCC:</strong> Uganda Communications Commission.</li><li><strong>Data Protection Act:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Ugandan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Uganda.'
    },
    'Ethiopia': {
        flag: '🇪🇹',
        compliance: '<ul><li><strong>ECSA:</strong> Ethiopian Communications Service Authority.</li><li><strong>State Monopoly:</strong> Ethio Telecom is primary carrier.</li><li><strong>Government Oversight:</strong> Subject to government regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Ethiopian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited availability for two-way messaging.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Ethiopia.'
    },
    'Zimbabwe': {
        flag: '🇿🇼',
        compliance: '<ul><li><strong>POTRAZ:</strong> Postal and Telecommunications Regulatory Authority.</li><li><strong>Sender Registration:</strong> Required with operators.</li><li><strong>Local Requirements:</strong> May require local business presence.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Zimbabwean Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Zimbabwe.'
    },

    // SOUTH AMERICA
    'Brazil': {
        flag: '🇧🇷',
        compliance: '<ul><li><strong>ANATEL:</strong> Brazilian telecom regulator oversight.</li><li><strong>LGPD:</strong> Brazilian data protection law (similar to GDPR).</li><li><strong>Opt-in Required:</strong> Explicit consent for marketing messages.</li><li><strong>Local Presence:</strong> Some use cases require Brazilian entity registration.</li></ul>',
        recommendedSender: 'Brazilian Long Code',
        backupSender: 'Alphanumeric Sender ID (for one-way)',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Full two-way messaging supported on Brazilian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API highly recommended—Brazil has one of the highest WhatsApp adoption rates globally.',
        rcs: 'Yes',
        rcsNotes: 'RCS is supported in Brazil via major carriers including Claro, TIM, Vivo, and Oi. Requires brand verification and ANATEL compliance.'
    },
    'Argentina': {
        flag: '🇦🇷',
        compliance: '<ul><li><strong>ENACOM:</strong> Argentine telecom regulator.</li><li><strong>PDPA:</strong> Personal Data Protection Act compliance.</li><li><strong>Opt-in:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Argentine Long Code',
        backupSender: 'Alphanumeric Sender ID',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Argentine long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. Very high adoption rate.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Argentina. Available on select carriers.'
    },
    'Chile': {
        flag: '🇨🇱',
        compliance: '<ul><li><strong>SUBTEL:</strong> Undersecretariat of Telecommunications.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required with carriers.</li></ul>',
        recommendedSender: 'Chilean Long Code',
        backupSender: 'Alphanumeric Sender ID',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Chilean long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support is developing in Chile via major carriers.'
    },
    'Colombia': {
        flag: '🇨🇴',
        compliance: '<ul><li><strong>CRC:</strong> Communications Regulation Commission.</li><li><strong>Habeas Data:</strong> Constitutional right to data privacy.</li><li><strong>Opt-in:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Colombian Long Code',
        backupSender: 'Alphanumeric Sender ID',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Colombian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available. High adoption rate.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Colombia.'
    },
    'Peru': {
        flag: '🇵🇪',
        compliance: '<ul><li><strong>OSIPTEL:</strong> Peruvian telecom regulator.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Peruvian Long Code',
        backupSender: 'Alphanumeric Sender ID',
        twoWayMessaging: 'Yes',
        twoWayNotes: 'Two-way messaging supported on Peruvian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Peru.'
    },
    'Venezuela': {
        flag: '🇻🇪',
        compliance: '<ul><li><strong>CONATEL:</strong> Venezuelan telecom regulator.</li><li><strong>Government Oversight:</strong> Subject to strict government regulations.</li><li><strong>Local Requirements:</strong> May require local presence.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Venezuelan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Venezuela.'
    },
    'Ecuador': {
        flag: '🇪🇨',
        compliance: '<ul><li><strong>ARCOTEL:</strong> Ecuadorian telecom regulator.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required with carriers.</li></ul>',
        recommendedSender: 'Ecuadorian Long Code',
        backupSender: 'Alphanumeric Sender ID',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Ecuadorian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Ecuador.'
    },
    'Bolivia': {
        flag: '🇧🇴',
        compliance: '<ul><li><strong>ATT:</strong> Telecommunications and Transport Authority.</li><li><strong>Data Protection:</strong> Bolivian data protection regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Bolivian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Bolivia.'
    },
    'Paraguay': {
        flag: '🇵🇾',
        compliance: '<ul><li><strong>CONATEL:</strong> Paraguayan telecom regulator.</li><li><strong>Data Protection:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Paraguayan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Paraguay.'
    },
    'Uruguay': {
        flag: '🇺🇾',
        compliance: '<ul><li><strong>URSEC:</strong> Uruguayan telecom regulator.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Uruguayan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Uruguay.'
    },

    // CARIBBEAN & CENTRAL AMERICA
    'Costa Rica': {
        flag: '🇨🇷',
        compliance: '<ul><li><strong>SUTEL:</strong> Costa Rican telecom regulator.</li><li><strong>Data Protection:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required with carriers.</li></ul>',
        recommendedSender: 'Costa Rican Long Code',
        backupSender: 'Alphanumeric Sender ID',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Costa Rican long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Costa Rica.'
    },
    'Panama': {
        flag: '🇵🇦',
        compliance: '<ul><li><strong>ASEP:</strong> Panamanian telecom regulator.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Panamanian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Panama.'
    },
    'Guatemala': {
        flag: '🇬🇹',
        compliance: '<ul><li><strong>SIT:</strong> Guatemalan telecom regulator.</li><li><strong>Data Protection:</strong> Guatemalan data protection regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Guatemalan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Guatemala.'
    },
    'Honduras': {
        flag: '🇭🇳',
        compliance: '<ul><li><strong>CONATEL:</strong> Honduran telecom regulator.</li><li><strong>Data Protection:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Honduran Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Honduras.'
    },
    'El Salvador': {
        flag: '🇸🇻',
        compliance: '<ul><li><strong>SIGET:</strong> El Salvador telecom regulator.</li><li><strong>Data Protection:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Salvadoran Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in El Salvador.'
    },
    'Nicaragua': {
        flag: '🇳🇮',
        compliance: '<ul><li><strong>TELCOR:</strong> Nicaraguan telecom regulator.</li><li><strong>Data Protection:</strong> Local data protection regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Nicaraguan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Nicaragua.'
    },
    'Dominican Republic': {
        flag: '🇩🇴',
        compliance: '<ul><li><strong>INDOTEL:</strong> Dominican telecom regulator.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Dominican Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Dominican long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Dominican Republic.'
    },
    'Jamaica': {
        flag: '🇯🇲',
        compliance: '<ul><li><strong>OUR:</strong> Office of Utilities Regulation.</li><li><strong>Data Protection Act:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Jamaican Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Jamaica.'
    },
    'Trinidad and Tobago': {
        flag: '🇹🇹',
        compliance: '<ul><li><strong>TATT:</strong> Telecommunications Authority.</li><li><strong>Data Protection:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Trinidad Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Trinidad and Tobago.'
    },
    'Barbados': {
        flag: '🇧🇧',
        compliance: '<ul><li><strong>FTC:</strong> Fair Trading Commission oversight.</li><li><strong>Data Protection:</strong> Barbadian data protection regulations.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Barbadian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Barbados.'
    },

    // ADDITIONAL EUROPEAN COUNTRIES
    'Luxembourg': {
        flag: '🇱🇺',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>ILR:</strong> Luxembourg telecom regulator.</li><li><strong>Opt-in:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Luxembourg Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Alphanumeric IDs are one-way.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'Limited',
        rcsNotes: 'RCS support via Luxembourg carriers is developing.'
    },
    'Malta': {
        flag: '🇲🇹',
        compliance: '<ul><li><strong>GDPR:</strong> EU compliance required.</li><li><strong>MCA:</strong> Malta Communications Authority.</li><li><strong>Consent:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Maltese Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Maltese long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not widely available in Malta.'
    },
    'Cyprus': {
        flag: '🇨🇾',
        compliance: '<ul><li><strong>GDPR:</strong> EU data protection compliance.</li><li><strong>OCECPR:</strong> Cyprus telecom regulator.</li><li><strong>Opt-in:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Cypriot Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Cyprus.'
    },
    'Albania': {
        flag: '🇦🇱',
        compliance: '<ul><li><strong>AKEP:</strong> Albanian telecom regulator.</li><li><strong>Data Protection:</strong> Albanian data protection regulations.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Albanian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Albania.'
    },
    'North Macedonia': {
        flag: '🇲🇰',
        compliance: '<ul><li><strong>AEC:</strong> Macedonian telecom regulator.</li><li><strong>Data Protection:</strong> Local data protection regulations.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Macedonian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in North Macedonia.'
    },
    'Bosnia and Herzegovina': {
        flag: '🇧🇦',
        compliance: '<ul><li><strong>RAK:</strong> Bosnian telecom regulator.</li><li><strong>Data Protection:</strong> Local data protection regulations.</li><li><strong>Consent:</strong> Required for marketing.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Bosnian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Bosnia and Herzegovina.'
    },
    'Montenegro': {
        flag: '🇲🇪',
        compliance: '<ul><li><strong>AEKOM:</strong> Montenegro telecom regulator.</li><li><strong>Data Protection:</strong> Montenegrin regulations.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Montenegrin Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Montenegro.'
    },

    // ADDITIONAL ASIAN COUNTRIES
    'Cambodia': {
        flag: '🇰🇭',
        compliance: '<ul><li><strong>MPTC:</strong> Cambodian telecom regulator.</li><li><strong>Data Protection:</strong> Local data protection regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Cambodian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Cambodia.'
    },
    'Laos': {
        flag: '🇱🇦',
        compliance: '<ul><li><strong>MPT:</strong> Laos telecom regulator.</li><li><strong>Government Oversight:</strong> Subject to government regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Laotian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Laos.'
    },
    'Myanmar': {
        flag: '🇲🇲',
        compliance: '<ul><li><strong>MCIT:</strong> Ministry of Communications and Information Technology.</li><li><strong>SIM Registration:</strong> Strict SIM registration requirements.</li><li><strong>Government Oversight:</strong> Subject to military government regulations.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Myanmar Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited availability due to political situation.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available but subject to government restrictions.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Myanmar.'
    },
    'Brunei': {
        flag: '🇧🇳',
        compliance: '<ul><li><strong>AITI:</strong> Authority for Info-communications Technology Industry.</li><li><strong>Data Protection:</strong> Bruneian regulations.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Brunei Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Brunei.'
    },
    'Maldives': {
        flag: '🇲🇻',
        compliance: '<ul><li><strong>CAM:</strong> Communications Authority of Maldives.</li><li><strong>Data Protection:</strong> Maldivian regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Maldives Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Maldives.'
    },
    'Afghanistan': {
        flag: '🇦🇫',
        compliance: '<ul><li><strong>ATRA:</strong> Afghanistan Telecom Regulatory Authority.</li><li><strong>Government Oversight:</strong> Subject to Taliban government regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Afghan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited availability due to political situation.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available but subject to government restrictions.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Afghanistan.'
    },
    'Kazakhstan': {
        flag: '🇰🇿',
        compliance: '<ul><li><strong>Ministry of Digital Development:</strong> Kazakh telecom oversight.</li><li><strong>Data Localization:</strong> May require data storage in Kazakhstan.</li><li><strong>Sender Registration:</strong> Required with carriers.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Kazakh Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Kazakh long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Kazakhstan.'
    },
    'Uzbekistan': {
        flag: '🇺🇿',
        compliance: '<ul><li><strong>UZCI:</strong> Uzbek telecom regulator.</li><li><strong>Government Oversight:</strong> Subject to government regulations.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Uzbek Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Uzbekistan.'
    },
    'Azerbaijan': {
        flag: '🇦🇿',
        compliance: '<ul><li><strong>Ministry of Transport:</strong> Azerbaijani telecom oversight.</li><li><strong>Data Protection:</strong> Local data protection regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Azerbaijani Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Azerbaijan.'
    },
    'Georgia': {
        flag: '🇬🇪',
        compliance: '<ul><li><strong>GNCC:</strong> Georgian National Communications Commission.</li><li><strong>Data Protection:</strong> Georgian regulations.</li><li><strong>Consent:</strong> Required for marketing messages.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Georgian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Georgia.'
    },
    'Armenia': {
        flag: '🇦🇲',
        compliance: '<ul><li><strong>PSRC:</strong> Public Services Regulatory Commission.</li><li><strong>Data Protection:</strong> Armenian regulations.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Armenian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Armenia.'
    },

    // ADDITIONAL MIDDLE EAST
    'Iraq': {
        flag: '🇮🇶',
        compliance: '<ul><li><strong>CMC:</strong> Communications and Media Commission.</li><li><strong>Government Oversight:</strong> Subject to government regulations.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Iraqi Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Iraq.'
    },
    'Syria': {
        flag: '🇸🇾',
        compliance: '<ul><li><strong>MoT:</strong> Ministry of Telecommunications.</li><li><strong>Government Control:</strong> Strict government oversight of all communications.</li><li><strong>Sanctions:</strong> International sanctions may affect services.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Syrian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Very limited due to political situation and sanctions.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp Business API may be restricted due to sanctions.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Syria.'
    },
    'Yemen': {
        flag: '🇾🇪',
        compliance: '<ul><li><strong>TPA:</strong> Telecommunications and Post Authority.</li><li><strong>Civil Conflict:</strong> Services severely affected by ongoing conflict.</li><li><strong>Limited Infrastructure:</strong> Telecommunications infrastructure damaged.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Yemeni Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Very limited due to ongoing conflict and infrastructure damage.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp Business API available but unreliable due to conflict.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Yemen.'
    },

    // ADDITIONAL AFRICAN COUNTRIES
    'Algeria': {
        flag: '🇩🇿',
        compliance: '<ul><li><strong>ARPT:</strong> Algerian telecom regulator.</li><li><strong>Government Oversight:</strong> Subject to government regulations.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Algerian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Algerian long codes.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Algeria.'
    },
    'Tunisia': {
        flag: '🇹🇳',
        compliance: '<ul><li><strong>INT:</strong> Tunisian telecom regulator.</li><li><strong>Data Protection:</strong> Tunisian regulations.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Tunisian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging availability.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Tunisia.'
    },
    'Libya': {
        flag: '🇱🇾',
        compliance: '<ul><li><strong>GPC:</strong> General Post and Telecommunications Company.</li><li><strong>Political Instability:</strong> Services affected by ongoing instability.</li><li><strong>Limited Regulation:</strong> Regulatory framework is weak.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Libyan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Very limited due to political instability.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp Business API available but unreliable.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Libya.'
    },
    'Sudan': {
        flag: '🇸🇩',
        compliance: '<ul><li><strong>NTC:</strong> National Telecommunications Corporation.</li><li><strong>Political Instability:</strong> Services affected by ongoing conflict.</li><li><strong>Government Oversight:</strong> Subject to government control.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Sudanese Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Very limited due to ongoing conflict.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp Business API availability affected by political situation.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Sudan.'
    },
    'Senegal': {
        flag: '🇸🇳',
        compliance: '<ul><li><strong>ARTP:</strong> Senegalese telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Senegalese Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Senegal.'
    },
    'Ivory Coast': {
        flag: '🇨🇮',
        compliance: '<ul><li><strong>ARTCI:</strong> Ivorian telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Ivorian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Ivory Coast.'
    },
    'Cameroon': {
        flag: '🇨🇲',
        compliance: '<ul><li><strong>ART:</strong> Cameroon telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> Required with operators.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Cameroonian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Cameroon.'
    },
    'Mozambique': {
        flag: '🇲🇿',
        compliance: '<ul><li><strong>INCM:</strong> Mozambique telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Mozambican Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Mozambique.'
    },
    'Angola': {
        flag: '🇦🇴',
        compliance: '<ul><li><strong>INACOM:</strong> Angolan telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Angolan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Angola.'
    },
    'Zambia': {
        flag: '🇿🇲',
        compliance: '<ul><li><strong>ZICTA:</strong> Zambian telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Zambian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Zambia.'
    },
    'Botswana': {
        flag: '🇧🇼',
        compliance: '<ul><li><strong>BTA:</strong> Botswana Telecommunications Authority.</li><li><strong>Data Protection:</strong> Botswana regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Botswana Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Botswana.'
    },
    'Namibia': {
        flag: '🇳🇦',
        compliance: '<ul><li><strong>CRAN:</strong> Communications Regulatory Authority of Namibia.</li><li><strong>Data Protection:</strong> Namibian regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Namibian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Namibia.'
    },
    'Madagascar': {
        flag: '🇲🇬',
        compliance: '<ul><li><strong>ARTEC:</strong> Madagascar telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Malagasy Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Madagascar.'
    },
    'Mauritius': {
        flag: '🇲🇺',
        compliance: '<ul><li><strong>ICTA:</strong> Information and Communication Technologies Authority.</li><li><strong>Data Protection Act:</strong> Consent required for data processing.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Mauritian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Mauritius.'
    },
    'Rwanda': {
        flag: '🇷🇼',
        compliance: '<ul><li><strong>RURA:</strong> Rwanda Utilities Regulatory Authority.</li><li><strong>Data Protection:</strong> Rwandan regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Rwandan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Rwanda.'
    },
    'Malawi': {
        flag: '🇲🇼',
        compliance: '<ul><li><strong>MACRA:</strong> Malawi Communications Regulatory Authority.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Malawian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Malawi.'
    },

    // PACIFIC ISLANDS
    'Fiji': {
        flag: '🇫🇯',
        compliance: '<ul><li><strong>CAF:</strong> Communications Authority of Fiji.</li><li><strong>Data Protection:</strong> Fijian regulations.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Fijian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Fiji.'
    },
    'Papua New Guinea': {
        flag: '🇵🇬',
        compliance: '<ul><li><strong>NICTA:</strong> PNG telecom regulator.</li><li><strong>Data Protection:</strong> Local regulations.</li><li><strong>Sender Registration:</strong> May be required.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'PNG Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited two-way messaging support.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Papua New Guinea.'
    },

    // RUSSIA & NEIGHBORS
    'Russia': {
        flag: '🇷🇺',
        compliance: '<ul><li><strong>Roskomnadzor:</strong> Russian telecom and media regulator.</li><li><strong>Data Localization Law:</strong> Data must be stored on servers within Russia.</li><li><strong>Sender Registration:</strong> Required with Russian operators.</li><li><strong>International Sanctions:</strong> May affect service availability.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID (registered)',
        backupSender: 'Russian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging requires Russian long codes and local registration.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp Business API available but subject to government restrictions and potential blocking.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Russia due to sanctions and local regulations.'
    },
    'Ukraine': {
        flag: '🇺🇦',
        compliance: '<ul><li><strong>NCEC:</strong> National Commission for Electronic Communications.</li><li><strong>Data Protection Law:</strong> Consent required for data processing.</li><li><strong>War Impact:</strong> Services affected by ongoing conflict.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Ukrainian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Service reliability affected by ongoing conflict.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Ukraine.'
    },
    'Belarus': {
        flag: '🇧🇾',
        compliance: '<ul><li><strong>Ministry of Communications:</strong> Belarusian telecom oversight.</li><li><strong>Government Control:</strong> Strict government oversight of communications.</li><li><strong>Data Localization:</strong> May require data storage in Belarus.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Belarusian Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Limited availability due to government restrictions.',
        whatsapp: 'Limited',
        whatsappNotes: 'WhatsApp Business API may be restricted by government.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Belarus.'
    },
    'Moldova': {
        flag: '🇲🇩',
        compliance: '<ul><li><strong>ANRCETI:</strong> Moldovan telecom regulator.</li><li><strong>Data Protection:</strong> Moldovan regulations.</li><li><strong>Consent:</strong> Required for commercial messaging.</li></ul>',
        recommendedSender: 'Alphanumeric Sender ID',
        backupSender: 'Moldovan Long Code',
        twoWayMessaging: 'Limited',
        twoWayNotes: 'Two-way messaging availability is limited.',
        whatsapp: 'Yes',
        whatsappNotes: 'WhatsApp Business API available.',
        rcs: 'No',
        rcsNotes: 'RCS is not available in Moldova.'
    }
};
